# Generated by Django 5.1.6 on 2025-02-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todotask', '0002_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='desctiption',
            new_name='description',
        ),
    ]
